name: Deploy React App to EC2

on:
  push:
    branches:
      - main # Cambia 'main' por 'master' si esa es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest # Elige el runner de GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Clona tu repositorio en el runner

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Configura Node.js en el runner
        with:
          node-version: '20' # Usa la versión de Node.js que necesites para tu app

      - name: Install dependencies
        run: npm install # Instala las dependencias de tu proyecto

      - name: Build React App
        run: npm run build # Compila tu aplicación React. Esto creará la carpeta 'dist/'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10 # Mantén esta versión
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          # NUEVO PARÁMETRO: Intenta activar la sincronización/copia de esta manera
          sync: true # <--- AÑADE ESTA LÍNEA

          source: "dist/"
          target: "/var/www/tu-app-react/"

          script: |
            sudo rm -rf /var/www/tu-app-react/*
            sudo systemctl restart nginx