name: Deploy React App to EC2 (Git Pull with PNK subfolder)

on:
  push:
    branches:
      - main # Se dispara con cada push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest # El runner de GitHub Actions

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10 # Usamos esta acción para ejecutar comandos en EC2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # --- Comandos ejecutados directamente en tu instancia EC2 ---

            BASE_APP_DIR="/var/www/tu-app-react"
            APP_REPO_DIR="$BASE_APP_DIR/PNK" # La ruta completa donde estará el repositorio Git

            echo "Asegurando que el directorio base '$BASE_APP_DIR' exista..."
            sudo mkdir -p "$BASE_APP_DIR"
            # Asegura que el usuario que ejecuta el script tenga permisos sobre el directorio base
            sudo chown -R ${{ secrets.EC2_USER }}:$(id -gn ${{ secrets.EC2_USER }}) "$BASE_APP_DIR"

            # Verificar si el repositorio ya ha sido clonado en la subcarpeta 'PNK'
            if [ -d "$APP_REPO_DIR/.git" ]; then
              echo "Repositorio PNK ya clonado, navegando a '$APP_REPO_DIR' y haciendo pull..."
              cd "$APP_REPO_DIR"
              git pull origin main # Actualiza la rama main

            else
              echo "Repositorio PNK NO clonado, realizando clonación inicial en la subcarpeta..."
              cd "$BASE_APP_DIR" # Cambia al directorio base para clonar
              git clone https://github.com/PandaAkiraNakai/PNK.git PNK # Clona el repositorio en la subcarpeta PNK
              echo "Clonación inicial completa en: '$APP_REPO_DIR'"
              cd "$APP_REPO_DIR" # Navega a la subcarpeta recién clonada para los siguientes comandos
            fi

            echo "Instalando dependencias (si hay cambios en package.json) en '$APP_REPO_DIR'..."
            npm install # Se ejecuta dentro de $APP_REPO_DIR

            echo "Construyendo la aplicación React en '$APP_REPO_DIR'..."
            npm run build # Se ejecuta dentro de $APP_REPO_DIR, creando 'dist' en '$APP_REPO_DIR/dist'

            echo "Reiniciando Nginx para servir la nueva versión..."
            sudo systemctl restart nginx
